### ISSUE TITLE
Genome Doubling Not Documented

### ISSUE THREAD

**Issue by DarioS** [KChen-lab/Texomer#5]
The latest release has a genome doubling analysis feature but none of the documentation explains which output file the whole genome duplication status is in. Also, is there any estimate of if SNVs happen before genome doubling or after it?

**Comment by Fang0828** [comment]
Whole-genome doubling (WGD) estimates the proportion of amplified genomic region. The description was added to README. Texomer hasn't incorporated the estimation of timing for SNVs and genome doubling.
